modLoader="javafml"
loaderVersion="[32,)"
license="CoFH \"Don't Be a Jerk\" License"

[[mods]]
	modId="brandonscore"
	displayName="Brandon's Core"
    version="${version}"
	authors="brandon3055"
	description=''''''
    updateJSONURL="https://version-check.covers1624.net/check/?mod=BrandonsCore&mc=${mc_version}"

[[dependencies.brandonscore]]
    modId="forge"
    mandatory=true
    versionRange="[35.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brandonscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brandonscore]]
    modId="codechickenlib"
    mandatory=true
    versionRange="${ccl_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.brandonscore]]
	modId="projectintelligence"
	mandatory=false
	versionRange="[${pi_version},)"
	ordering="NONE"
	side="BOTH"
